export const APP_CONSTANTS = {
  MIN_PASSWORD_LENGTH: 8,
  MIN_PHONE_NUMBER_LENGTH: 17,
  MAX_PHOTO_COUNT: 5,
  DEFAULT_WAITING_TIME: 5,
  MAX_TITLE_LENGTH: 50,
  MAX_DESCRIPTION_LENGTH: 300,
};

export const MEDIA = {
  XSM: 480,
  SM: 768,
  MD: 1024,
  LG: 1200,
};
