export const ROUTES = {
  SIGNIN: 'sign-in',
  SIGNUP: 'sign-up',
  PROFILE: 'profile',
  EDIT: 'edit',
  NEW_AD: 'new-ad',
  CONFIRM_EMAIL: 'email-confirm',
  FAVORTIES: 'favorites',
  MY_ADS: 'my-ads',
  REVIEWS: 'reviews',
  ADMIN: 'admin',
  PENDING: 'pending',
  MODERATION: 'moderation',
  USERS: 'users',
  CATEGORIES: 'categories',
  CITIES: 'cities',
  POST: 'post',
  ADS_SEARCH: 'ads-search',
  DEALS: 'deals',
  RESERVATIONS: 'reservations',
  RECOVER_PASSWORD: 'reset-password',
  HISTORY: 'history',
};
